spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1357
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password: '{cipher}AQBmDTygaV8i+lHRq7m/O4TAFkJ/A53ISMAQgjWAw9caLEUM9Nj4V9twnjb72tlaj9QwLAmTAsY8Q+tLeLukV7AC8Tv1mind33W0GW7fiejq7qgXFcroafdd5ADU/KVxypUBvdLSmbE3iThE+vO0bgzvw/tvDUk2idAJtnQ39OzRbMtcu68RI7LJHPblfhVc8iHQeQrPqifWGl5GDkUUzMJKQM8iNi36dLe3IxYV1PmhVDsOfe4M4kU6Vr3RKYM35TRtuXDQyhD0ejOs7UvFBcc2juOtQaCWb6JLYMEuhLeaDum9F700Ibr+Ggfz7fKfpufvVR0oWvpbY0bzlyS0YBB7PejdFdrtr1I9LkcM1/bM2UJm0y4/4svCV5szfxZW9HU='

#유저 도커용 입니다 
  
token:
  expiration_time: 864000000
  secret: '{cipher}AQBSTibIkDoa4vgGNtMfiTI660f+Uj7m2gDVPCG+rH13VFlnpWmEmnoZtK9Ih3NHYr3yJZuo6PCENNuwP2+oAAC2uMwnO/NPzq0HRbOMIkAY570w9x0ZS7NMiRAKJ4u3l6cSI2dAXzYhWSbBcVEiIrMdlL5kuL8ZOXUIAcheEkaKiWk1UTAEH3+russ6yvSHjqBKbW1y1Ofd085X/9wdccT++WnkCu3i4B5zy2MiGKFAWAXdKlQB+yKPqvwKH69tGSTehH1ZJ7/xaUCS2poWbDHrgVXM4SiHhdkQejAZY9Ai+boQgu5VuDUY3jl/kW9H2L0Gl5oBTjNQ43QfquRnnAjdNcWui2IP8OgueKS79yGH5gzhxHnV/gYdFPpn11jhAFA29lr97PAjXzEvZY2ywnhm'

order-service:
  url: http://ORDER-SERVICE/%s/orders
  exception:
    orders-is-empty: 'There is no items'  
